INSERT INTO item_mapping VALUES('Abaca, manila hemp, raw','Fibre Crops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Agave fibres, raw, n.e.c.','Fibre Crops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Almonds, in shell','Treenuts, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw','-','Crops, primary');
INSERT INTO item_mapping VALUES('Apples','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Apricots','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Areca nuts','-','Crops, primary');
INSERT INTO item_mapping VALUES('Artichokes','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Asparagus','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Asses','-','Live Animals');
INSERT INTO item_mapping VALUES('Avocados','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Balata, gutta-percha, guayule, chicle and similar natural gums in primary forms or in plates, sheets or strip','-','Crops, primary');
INSERT INTO item_mapping VALUES('Bambara beans, dry','Pulses, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Bananas','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Barley','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('Beans, dry','Pulses, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Beef and Buffalo Meat, primary','-','Livestock primary');
INSERT INTO item_mapping VALUES('Beer of barley, malted','-','Crops Processed');
INSERT INTO item_mapping VALUES('Bees','-','Live Animals');
INSERT INTO item_mapping VALUES('Beeswax','-','Livestock primary');
INSERT INTO item_mapping VALUES('Blueberries','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Brazil nuts, in shell','Treenuts, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Broad beans and horse beans, dry','Pulses, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Broad beans and horse beans, green','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Buckwheat','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('Buffalo','Cattle and Buffaloes','Live Animals');
INSERT INTO item_mapping VALUES('Buffalo fat, unrendered','-','Livestock primary');
INSERT INTO item_mapping VALUES('Butter and ghee of sheep milk','Butter and Ghee','Livestock processed');
INSERT INTO item_mapping VALUES('Butter of buffalo milk','Butter and Ghee','Livestock processed');
INSERT INTO item_mapping VALUES('Butter of cow milk','Butter and Ghee','Livestock processed');
INSERT INTO item_mapping VALUES('Butter of goat milk','Butter and Ghee','Livestock processed');
INSERT INTO item_mapping VALUES('Buttermilk, dry','Skim Milk & Buttermilk, Dry','Livestock processed');
INSERT INTO item_mapping VALUES('Cabbages','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Camels','-','Live Animals');
INSERT INTO item_mapping VALUES('Canary seed','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('Cantaloupes and other melons','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Carrots and turnips','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Cashew nuts, in shell','Treenuts, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Cashewapple','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Cassava leaves','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Cassava, fresh','Roots and Tubers, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Castor oil seeds','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Cattle','Cattle and Buffaloes','Live Animals');
INSERT INTO item_mapping VALUES('Cattle fat, unrendered','-','Livestock primary');
INSERT INTO item_mapping VALUES('Cauliflowers and broccoli','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Cereals n.e.c.','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('Cheese from milk of buffalo, fresh or processed','Cheese (All Kinds)','Livestock processed');
INSERT INTO item_mapping VALUES('Cheese from milk of goats, fresh or processed','Cheese (All Kinds)','Livestock processed');
INSERT INTO item_mapping VALUES('Cheese from milk of sheep, fresh or processed','Cheese (All Kinds)','Livestock processed');
INSERT INTO item_mapping VALUES('Cheese from skimmed cow milk','Cheese (All Kinds)','Livestock processed');
INSERT INTO item_mapping VALUES('Cheese from whole cow milk','Cheese (All Kinds)','Livestock processed');
INSERT INTO item_mapping VALUES('Cherries','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Chestnuts, in shell','Treenuts, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Chick peas, dry','Pulses, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Chickens','Poultry Birds','Live Animals');
INSERT INTO item_mapping VALUES('Chicory roots','-','Crops, primary');
INSERT INTO item_mapping VALUES('Chillies and peppers, dry (Capsicum spp., Pimenta spp.), raw','-','Crops, primary');
INSERT INTO item_mapping VALUES('Chillies and peppers, green (Capsicum spp. and Pimenta spp.)','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Cinnamon and cinnamon-tree flowers, raw','-','Crops, primary');
INSERT INTO item_mapping VALUES('Citrus Fruit, Total','-','Crops, primary');
INSERT INTO item_mapping VALUES('Cloves (whole stems), raw','-','Crops, primary');
INSERT INTO item_mapping VALUES('Cocoa beans','-','Crops, primary');
INSERT INTO item_mapping VALUES('Coconut oil','-','Crops Processed');
INSERT INTO item_mapping VALUES('Coconuts, in shell','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Coffee, green','-','Crops, primary');
INSERT INTO item_mapping VALUES('Coir, raw','-','Crops, primary');
INSERT INTO item_mapping VALUES('Cotton lint, ginned','-','Crops Processed');
INSERT INTO item_mapping VALUES('Cotton seed','-','Crops Processed');
INSERT INTO item_mapping VALUES('Cottonseed oil','-','Crops Processed');
INSERT INTO item_mapping VALUES('Cow peas, dry','Pulses, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Cranberries','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Cream, fresh','-','Livestock processed');
INSERT INTO item_mapping VALUES('Crops, primary','-','Crops, primary');
INSERT INTO item_mapping VALUES('Cucumbers and gherkins','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Currants','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Dates','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Ducks','Poultry Birds','Live Animals');
INSERT INTO item_mapping VALUES('Edible offal of buffalo, fresh, chilled or frozen','-','Livestock primary');
INSERT INTO item_mapping VALUES('Edible offal of cattle, fresh, chilled or frozen','-','Livestock primary');
INSERT INTO item_mapping VALUES('Edible offal of goat, fresh, chilled or frozen','-','Livestock primary');
INSERT INTO item_mapping VALUES('Edible offal of pigs, fresh, chilled or frozen','-','Livestock primary');
INSERT INTO item_mapping VALUES('Edible offal of sheep, fresh, chilled or frozen','-','Livestock primary');
INSERT INTO item_mapping VALUES('Edible offals of camels and other camelids, fresh, chilled or frozen','-','Livestock primary');
INSERT INTO item_mapping VALUES('Edible offals of horses and other equines,  fresh, chilled or frozen','-','Livestock primary');
INSERT INTO item_mapping VALUES('Edible roots and tubers with high starch or inulin content, n.e.c., fresh','Roots and Tubers, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Eggplants (aubergines)','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Eggs from other birds in shell, fresh, n.e.c.','Eggs Primary','Livestock primary');
INSERT INTO item_mapping VALUES('Fat of camels','-','Livestock primary');
INSERT INTO item_mapping VALUES('Fat of pigs','-','Livestock primary');
INSERT INTO item_mapping VALUES('Fibre Crops, Fibre Equivalent','-','Crops, primary');
INSERT INTO item_mapping VALUES('Figs','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Flax, raw or retted','Fibre Crops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Fonio','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('Game meat, fresh, chilled or frozen','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Geese','Poultry Birds','Live Animals');
INSERT INTO item_mapping VALUES('Ghee from buffalo milk','Butter and Ghee','Livestock processed');
INSERT INTO item_mapping VALUES('Ghee from cow milk','Butter and Ghee','Livestock processed');
INSERT INTO item_mapping VALUES('Ginger, raw','-','Crops, primary');
INSERT INTO item_mapping VALUES('Goat fat, unrendered','-','Livestock primary');
INSERT INTO item_mapping VALUES('Goats','Sheep and Goats','Live Animals');
INSERT INTO item_mapping VALUES('Gooseberries','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Grapes','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Green corn (maize)','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Green garlic','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Green tea (not fermented), black tea (fermented) and partly fermented tea, in immediate packings of a content not exceeding 3 kg','-','Crops Processed');
INSERT INTO item_mapping VALUES('Groundnut oil','-','Crops Processed');
INSERT INTO item_mapping VALUES('Groundnuts, excluding shelled','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Hazelnuts, in shell','Treenuts, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Hempseed','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Hen eggs in shell, fresh','Eggs Primary','Livestock primary');
INSERT INTO item_mapping VALUES('Hop cones','-','Crops, primary');
INSERT INTO item_mapping VALUES('Horse meat, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Horses','-','Live Animals');
INSERT INTO item_mapping VALUES('Jojoba seeds','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Jute, raw or retted','Fibre Crops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Kapok fibre, raw','-','Crops Processed');
INSERT INTO item_mapping VALUES('Kapok fruit','-','Crops, primary');
INSERT INTO item_mapping VALUES('Kapokseed in shell','-','Crops Processed');
INSERT INTO item_mapping VALUES('Karite nuts (sheanuts)','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Kenaf, and other textile bast fibres, raw or retted','Fibre Crops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Kiwi fruit','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Kola nuts','-','Crops, primary');
INSERT INTO item_mapping VALUES('Leeks and other alliaceous vegetables','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Lemons and limes','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Lentils, dry','Pulses, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Lettuce and chicory','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Linseed','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Live Animals','-','Live Animals');
INSERT INTO item_mapping VALUES('Locust beans (carobs)','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Lupins','Pulses, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Maize (corn)','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('Mangoes, guavas and mangosteens','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Margarine and shortening','-','Crops Processed');
INSERT INTO item_mapping VALUES('Maté leaves','-','Crops, primary');
INSERT INTO item_mapping VALUES('Meat of asses, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of buffalo, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of camels, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of cattle with the bone, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of chickens, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of ducks, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of geese, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of goat, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of mules, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of other domestic camelids, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of other domestic rodents, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of pig with the bone, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of pigeons and other birds n.e.c., fresh, chilled or frozen','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of rabbits and hares, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of sheep, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat of turkeys, fresh or chilled','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Meat, Poultry','-','Livestock primary');
INSERT INTO item_mapping VALUES('Melonseed','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Millet','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('Mixed grain','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('Molasses','-','Crops Processed');
INSERT INTO item_mapping VALUES('Mules and hinnies','-','Live Animals');
INSERT INTO item_mapping VALUES('Mushrooms and truffles','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Mustard seed','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Natural honey','-','Livestock primary');
INSERT INTO item_mapping VALUES('Natural rubber in primary forms','-','Crops, primary');
INSERT INTO item_mapping VALUES('Nutmeg, mace, cardamoms, raw','-','Crops, primary');
INSERT INTO item_mapping VALUES('Oats','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('Oil of linseed','-','Crops Processed');
INSERT INTO item_mapping VALUES('Oil of maize','-','Crops Processed');
INSERT INTO item_mapping VALUES('Oil of palm kernel','-','Crops Processed');
INSERT INTO item_mapping VALUES('Oil of sesame seed','-','Crops Processed');
INSERT INTO item_mapping VALUES('Oil palm fruit','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Oilcrops, Cake Equivalent','-','Crops, primary');
INSERT INTO item_mapping VALUES('Oilcrops, Oil Equivalent','-','Crops, primary');
INSERT INTO item_mapping VALUES('Okra','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Olive oil','-','Crops Processed');
INSERT INTO item_mapping VALUES('Olives','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Onions and shallots, dry (excluding dehydrated)','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Onions and shallots, green','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Oranges','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Other beans, green','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Other berries and fruits of the genus vaccinium n.e.c.','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Other birds','Poultry Birds','Live Animals');
INSERT INTO item_mapping VALUES('Other camelids','-','Live Animals');
INSERT INTO item_mapping VALUES('Other citrus fruit, n.e.c.','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Other fibre crops, raw, n.e.c.','Fibre Crops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Other fruits, n.e.c.','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Other meat n.e.c. (excluding mammals), fresh, chilled or frozen','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Other nuts (excluding wild edible nuts and groundnuts), in shell, n.e.c.','Treenuts, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Other oil seeds, n.e.c.','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Other pome fruits','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Other pulses n.e.c.','Pulses, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Other rodents','-','Live Animals');
INSERT INTO item_mapping VALUES('Other stimulant, spice and aromatic crops, n.e.c.','-','Crops, primary');
INSERT INTO item_mapping VALUES('Other stone fruits','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Other sugar crops n.e.c.','Sugar Crops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Other tropical fruits, n.e.c.','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Other vegetables, fresh n.e.c.','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Palm kernels','-','Crops Processed');
INSERT INTO item_mapping VALUES('Palm oil','-','Crops Processed');
INSERT INTO item_mapping VALUES('Papayas','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Peaches and nectarines','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Pears','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Peas, dry','Pulses, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Peas, green','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Pepper (Piper spp.), raw','-','Crops, primary');
INSERT INTO item_mapping VALUES('Peppermint, spearmint','-','Crops, primary');
INSERT INTO item_mapping VALUES('Persimmons','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Pig fat, rendered','-','Livestock processed');
INSERT INTO item_mapping VALUES('Pigeon peas, dry','Pulses, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Pineapples','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Pistachios, in shell','Treenuts, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Plantains and cooking bananas','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Plums and sloes','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Pomelos and grapefruits','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Poppy seed','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Potatoes','Roots and Tubers, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Pumpkins, squash and gourds','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Pyrethrum, dried flowers','-','Crops, primary');
INSERT INTO item_mapping VALUES('Quinces','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Quinoa','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('Rabbits and hares','-','Live Animals');
INSERT INTO item_mapping VALUES('Ramie, raw or retted','Fibre Crops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Rape or colza seed','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Rapeseed or canola oil, crude','-','Crops Processed');
INSERT INTO item_mapping VALUES('Raspberries','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Raw cane or beet sugar (centrifugal only)','-','Crops Processed');
INSERT INTO item_mapping VALUES('Raw hides and skins of buffaloes','Hides and skins, primary','Livestock primary');
INSERT INTO item_mapping VALUES('Raw hides and skins of cattle','Hides and skins, primary','Livestock primary');
INSERT INTO item_mapping VALUES('Raw hides and skins of goats or kids','Hides and skins, primary','Livestock primary');
INSERT INTO item_mapping VALUES('Raw hides and skins of sheep or lambs','Hides and skins, primary','Livestock primary');
INSERT INTO item_mapping VALUES('Raw milk of buffalo','Milk, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Raw milk of camel','Milk, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Raw milk of cattle','Milk, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Raw milk of goats','Milk, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Raw milk of sheep','Milk, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Raw silk (not thrown)','-','Livestock processed');
INSERT INTO item_mapping VALUES('Rice','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('Rye','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('Safflower seed','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Safflower-seed oil, crude','-','Crops Processed');
INSERT INTO item_mapping VALUES('Seed cotton, unginned','-','Crops, primary');
INSERT INTO item_mapping VALUES('Sesame seed','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Sheep','Sheep and Goats','Live Animals');
INSERT INTO item_mapping VALUES('Sheep and Goat Meat','-','Livestock primary');
INSERT INTO item_mapping VALUES('Sheep fat, unrendered','-','Livestock primary');
INSERT INTO item_mapping VALUES('Shorn wool, greasy, including fleece-washed shorn wool','-','Livestock primary');
INSERT INTO item_mapping VALUES('Silk-worm cocoons suitable for reeling','-','Livestock primary');
INSERT INTO item_mapping VALUES('Sisal, raw','Fibre Crops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Skim milk and whey powder','Skim Milk & Buttermilk, Dry','Livestock processed');
INSERT INTO item_mapping VALUES('Skim milk of cows','-','Livestock processed');
INSERT INTO item_mapping VALUES('Skim milk, condensed','Evaporated & Condensed Milk','Livestock processed');
INSERT INTO item_mapping VALUES('Skim milk, evaporated','Evaporated & Condensed Milk','Livestock processed');
INSERT INTO item_mapping VALUES('Snails, fresh, chilled, frozen, dried, salted or in brine, except sea snails','Meat, Total','Livestock primary');
INSERT INTO item_mapping VALUES('Sorghum','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('Sour cherries','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Soya bean oil','-','Crops Processed');
INSERT INTO item_mapping VALUES('Soya beans','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Spinach','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Strawberries','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('String beans','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Sugar beet','Sugar Crops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Sugar cane','Sugar Crops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Sunflower seed','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Sunflower-seed oil, crude','-','Crops Processed');
INSERT INTO item_mapping VALUES('Sweet potatoes','Roots and Tubers, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Swine / pigs','-','Live Animals');
INSERT INTO item_mapping VALUES('Tallow','-','Livestock processed');
INSERT INTO item_mapping VALUES('Tallowtree seeds','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Tangerines, mandarins, clementines','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Taro','Roots and Tubers, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Tea leaves','-','Crops, primary');
INSERT INTO item_mapping VALUES('Tomatoes','Vegetables Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Triticale','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('True hemp, raw or retted','Fibre Crops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Tung nuts','Oilcrops Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Turkeys','Poultry Birds','Live Animals');
INSERT INTO item_mapping VALUES('Unmanufactured tobacco','-','Crops, primary');
INSERT INTO item_mapping VALUES('Vanilla, raw','-','Crops, primary');
INSERT INTO item_mapping VALUES('Vetches','Pulses, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Walnuts, in shell','Treenuts, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Watermelons','Fruit Primary','Crops, primary');
INSERT INTO item_mapping VALUES('Wheat','Cereals, primary','Crops, primary');
INSERT INTO item_mapping VALUES('Whey, condensed','Evaporated & Condensed Milk','Livestock processed');
INSERT INTO item_mapping VALUES('Whey, dry','-','Livestock processed');
INSERT INTO item_mapping VALUES('Whole milk powder','-','Livestock processed');
INSERT INTO item_mapping VALUES('Whole milk, condensed','Evaporated & Condensed Milk','Livestock processed');
INSERT INTO item_mapping VALUES('Whole milk, evaporated','Evaporated & Condensed Milk','Livestock processed');
INSERT INTO item_mapping VALUES('Wine','-','Crops Processed');
INSERT INTO item_mapping VALUES('Yams','Roots and Tubers, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Yautia','Roots and Tubers, Total','Crops, primary');
INSERT INTO item_mapping VALUES('Yoghurt','-','Livestock processed');
INSERT INTO item_mapping VALUES('Flax, processed but not spun','-','Crops Processed');